on:
    pull_request:
      types: [closed]
      branches:
        - main
      paths:
        - ".github/workflows/infrastructure.yml"
        - "infrastructure/**"

name: Deploy infrastructure
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    #chekout the code
    - name: Checkout
      uses: actions/checkout@main

    # Login to Azure
    - name: Login via Azure CLI
      id: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy infrastructure
    - name: Deploy infrastructure
      id: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: infrastructure/bicep/deploy-infra.bicep
        deploymentName: deploy-infra--${{ steps.params.outputs.commit_id }}
        deploymentMode: Incremental
        failOnStdErr: true
